#!name=Wink -Nightmarket
# 👤 Author: Marol62926
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  

[Script]
Soundcloud = type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,script-path=https://raw.githubusercontent.com/Marol62926/MarScrpt/main/soundcloud.js,requires-body=1,max-size=0

[MITM]
hostname = %APPEND% api-mobile.soundcloud.com
