#!name=SoundCloudPlus-Nightmarket
#!desc=SoundCloudPlus-Nightmarket
# 👤 Author: Marol62926
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  
[Script]
SoundCloudGo+=type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/Marol62926/MarScrpt/main/soundcloud.js
[MITM]
hostname= %APPEND% api-mobile.soundcloud.com
